import { useEffect, useMemo, useRef, useState } from "react";
import { AppShell } from "../../../shared/AppShell";
import { useNotesStore } from "../application/notesStore";
import type { Note } from "../domain/types";
import { notesGateway } from "../infrastructure/notesGateway";
import "./NotesPage.css";
import "./NotesSurface.css";

const initialContent = ":::objective\nRegistre decisões e mantenha o contexto do Project acessível.\n:::\n\n## Visão geral\n\n- [ ] Adicione uma tarefa\n\n```ts\nconst mode = 'local-first';\n```";
const stamp = (value: number) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(value);
function AssetPreviews({ projectId, content }: { projectId: string; content: string }) { const ids = [...content.matchAll(/asset:\/\/([\w-]+)/g)].map((match) => match[1]); const [images, setImages] = useState<Record<string, string>>({}); useEffect(() => { ids.forEach((id) => { if (images[id]) return; void notesGateway.readAsset(projectId, id).then((asset) => { let binary = ""; asset.bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); setImages((current) => ({ ...current, [id]: `data:${asset.mediaType};base64,${btoa(binary)}` })); }); }); }, [content, projectId]); return ids.length ? <div className="note-asset-previews">{ids.map((id) => images[id] ? <img key={id} src={images[id]} alt="Imagem anexada à Note" /> : <span key={id}>Carregando imagem...</span>)}</div> : null; }
void AssetPreviews;

function NotesList({ projectId }: { projectId: string }) {
  const state = useNotesStore();
  const visible = useMemo(() => state.notes.filter((note) => (state.filter !== "pinned" || note.isPinned) && (state.filter === "archived" ? note.isArchived : !note.isArchived) && (note.title + note.content).toLowerCase().includes(state.query.toLowerCase())), [state.notes, state.filter, state.query]);
  return <aside className="notes-list"><header><h1>Notes</h1><button className="notes-add" onClick={() => void state.create(projectId)} aria-label="Criar nova Note">＋</button></header><label className="notes-search"><span className="sr-only">Buscar Notes</span><input value={state.query} onChange={(event) => state.setQuery(event.target.value)} placeholder="Search notes..." /></label><div className="notes-filters" role="tablist">{(["all", "pinned", "archived"] as const).map((filter) => <button key={filter} className={state.filter === filter ? "active" : ""} onClick={() => state.setFilter(filter)}>{filter === "all" ? "All" : filter === "pinned" ? "Pinned" : "Archived"}</button>)}<button disabled>Shared</button></div><div className="notes-items">{state.loading ? <p>Carregando Notes...</p> : visible.length ? visible.map((note) => <button key={note.id} className={state.selectedId === note.id ? "note-row selected" : "note-row"} onClick={() => state.select(note.id)}><span className="note-row-icon">▱</span><span><strong>{note.title}</strong><small>{note.content.slice(0, 52) || "Nota em branco"}</small></span><time>{stamp(note.updatedAt)}</time>{note.isPinned && <i aria-label="Fixada">⌖</i>}</button>) : <p className="notes-empty-list">Nenhuma Note encontrada.</p>}</div></aside>;
}

function Editor({ projectId, note }: { projectId: string; note?: Note }) {
  const { save, archive, pin } = useNotesStore(); const [draft, setDraft] = useState<Note | undefined>(note); const [status, setStatus] = useState("Saved locally"); const imageInput = useRef<HTMLInputElement>(null);
  useEffect(() => setDraft(note), [note]);
  useEffect(() => { if (!draft || draft === note) return; setStatus("Salvando..."); const timer = window.setTimeout(() => { void save(projectId, draft).then(() => setStatus("Saved locally")); }, 600); return () => window.clearTimeout(timer); }, [draft, note, projectId, save]);
  if (!draft) return <main className="notes-editor notes-empty-editor"><strong>Selecione uma Note</strong><span>Crie uma Note para registrar uma ideia ou decisão.</span></main>;
  const content = draft.content || initialContent;
  const insertImage = (file?: File) => { if (!file || !file.type.startsWith("image/")) return; void file.arrayBuffer().then((buffer) => notesGateway.createAsset(projectId, { name: file.name, type: file.type, bytes: Array.from(new Uint8Array(buffer)) })).then((asset) => setDraft((current) => current ? { ...current, content: (current.content || initialContent) + "\n\n![" + file.name + "](asset://" + asset.id + ")" } : current)).catch(() => setStatus("Falha ao salvar imagem")); };
  return <main className="notes-editor"><header className="notes-editor-top"><span>Notes / {draft.title}</span><span>{status}</span></header><div className="notes-toolbar" aria-label="Ferramentas de edição"><button onClick={() => setDraft({ ...draft, content: "## " + content })}>H2</button><button onClick={() => setDraft({ ...draft, content: "**" + content + "**" })}>B</button><button onClick={() => setDraft({ ...draft, content: "- [ ] " + content })}>☑</button><button onClick={() => setDraft({ ...draft, content: "```ts\n" + content + "\n```" })}>Code</button><button onClick={() => imageInput.current?.click()}>Image</button><button disabled title="Disponível em uma próxima etapa">Link</button><input ref={imageInput} className="sr-only" type="file" accept="image/*" onChange={(event) => insertImage(event.target.files?.[0])} /></div><input className="notes-title-input" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} aria-label="Título da Note" /><textarea className="notes-content-input" value={content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} onPaste={(event) => { const image = Array.from(event.clipboardData.files).find((file) => file.type.startsWith("image/")); if (image) { event.preventDefault(); insertImage(image); } }} onDrop={(event) => { const image = Array.from(event.dataTransfer.files).find((file) => file.type.startsWith("image/")); if (image) { event.preventDefault(); insertImage(image); } }} onDragOver={(event) => event.preventDefault()} aria-label="Conteúdo em Markdown. Cole ou arraste imagens aqui." /><footer><button onClick={() => void pin(projectId, draft.id)}>{draft.isPinned ? "Desafixar" : "Fixar"}</button><button onClick={() => void archive(projectId, draft.id, !draft.isArchived)}>{draft.isArchived ? "Restaurar" : "Arquivar"}</button></footer></main>;
}

function Inspector({ note }: { note?: Note }) { const [tag, setTag] = useState(""); const { save } = useNotesStore(); if (!note) return <aside className="notes-inspector"><div className="inspector-tabs"><button className="active">Properties</button><button disabled>Backlinks (0)</button></div><p className="muted">As propriedades aparecerão ao selecionar uma Note.</p></aside>; const addTag = () => { if (!tag.trim() || note.tags.includes(tag.trim())) return; void save(note.projectId, { ...note, tags: [...note.tags, tag.trim()] }); setTag(""); }; return <aside className="notes-inspector"><div className="inspector-tabs"><button className="active">Properties</button><button disabled>Backlinks (0)</button></div><section><h2>Tags</h2><div className="note-tags">{note.tags.map((item) => <span key={item}>{item}</span>)}</div><input className="add-tag" value={tag} onChange={(event) => setTag(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addTag(); }} placeholder="Add tag" aria-label="Adicionar tag" /></section><section><h2>Date</h2><time>{stamp(note.updatedAt)}</time></section><section><h2>Author</h2><p><b>BG</b> Bruno G</p></section><section><h2>Related</h2><p className="muted">Nenhum link relacionado.</p></section><section className="ai-assist"><h2>AI Assist</h2><button disabled>Summarize</button><button disabled>Improve writing</button><button disabled>Create diagram</button></section></aside>; }

export default function NotesPage({ projectId }: { projectId: string }) { const { notes, selectedId, error, load } = useNotesStore(); useEffect(() => { void load(projectId); }, [load, projectId]); const selected = notes.find((note) => note.id === selectedId); return <AppShell activeSection="notes" onNavigate={(section) => { window.location.hash = section === "home" ? "" : section === "canvas" ? "canvas/" + projectId : section === "notes" ? "notes/" + projectId : section; }}><div className="notes-layout">{error ? <div className="notes-error" role="alert">{error}</div> : <><NotesList projectId={projectId} /><Editor projectId={projectId} note={selected} /><Inspector note={selected} /></>}</div></AppShell>; }
